name: Publish

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '47 10 * * *'

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: '3.9'
    - name: find e-books
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        python find.py
    - name: publish changes
      run: |
        git config --local user.email "blair@blairconrad.com"
        git config --local user.name "Blair Conrad [bot]"
        git add .
        git commit -m "Publish feed at $(date --iso-8601)" || echo "No changes"
        git push
