name: Publish

on:
  pull_request:
  push:
    branches: [ main ]
  schedule:
    - cron: '47 10 * * *'
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: find e-books
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        python find.py
    - name: push changes
      run: |
        if [ "${GITHUB_EVENT_NAME}" != "pull_request" ]
        then
          git config --local user.email "blair@blairconrad.com"
          git config --local user.name "Blair Conrad [bot]"
          git add .
          git commit -m "Publish feed at $(date --iso-8601)" || echo "No changes"
          git push
        fi
